
spring:
    application:
        name: city-service
    cloud:
        consul:
            host: 10.114.51.190
            port: 8500
            enabled: true
            discovery:
                ip-address: 10.114.12.11
                port: ${server.port}
                prefer-ip-address: true
                enabled: true
                health-check-url: http://${spring.cloud.consul.discovery.ip-address}:${server.port}/health
                health-check-interval: 10s
server:
    port: 8183
